### ISSUE TITLE
Doesn't work on Paper 1.16.2

### ISSUE THREAD

**Issue by rafitamolin** [Ashesh3/TelegramMinecraft#1]
I set up the bot token, the chat ID and everything's fine but when starting the plugin:

```
31.08 02:15:00 [Multicraft] Skipped 78 lines due to rate limit (30/s)
31.08 02:14:59 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1713) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1902) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:800) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at org.bukkit.Bukkit.reload(Bukkit.java:699) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.reload(CraftServer.java:938) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-168]
31.08 02:14:59 [Server] INFO at Main.TelegramReporter.Main.TelegramReporter.onEnable(TelegramReporter.java:45) ~[?:?]
31.08 02:14:59 [Server] INFO at Main.TelegramReporter.Telegram.getUpdates.<clinit>(getUpdates.java:20) ~[?:?]
31.08 02:14:59 [Server] INFO java.lang.NoClassDefFoundError: java/net/http/HttpClient
31.08 02:14:59 [Server] ERROR Error occurred while enabling TelegramReporter v2.1 (Is it up to date?)
31.08 02:14:59 [Server] INFO [TelegramReporter] Bot detected @magikeadorbot
31.08 02:14:59 [Server] INFO [TelegramReporter] Enabling TelegramReporter v2.1```

**Comment by ZeyNet** [comment]
use java 11+ maybe help
